// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7v9HOGh55eUjwyZV7zmv8HNgaUNBix4',
    appId: '1:291911333859:web:7891017e0f6ee737c012d6',
    messagingSenderId: '291911333859',
    projectId: 'qariconnect-9b95c',
    authDomain: 'qariconnect-9b95c.firebaseapp.com',
    storageBucket: 'qariconnect-9b95c.firebasestorage.app',
    measurementId: 'G-G3J54SDF3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUYa6d03TC97rJHJAEeL8RvTNn7O8PFnM',
    appId: '1:291911333859:android:b399e1922e51ccf9c012d6',
    messagingSenderId: '291911333859',
    projectId: 'qariconnect-9b95c',
    storageBucket: 'qariconnect-9b95c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8C7Cw7RLJwdZ5bG1cax3HQl6eBuQ42vg',
    appId: '1:291911333859:ios:70929548e49b9e8ec012d6',
    messagingSenderId: '291911333859',
    projectId: 'qariconnect-9b95c',
    storageBucket: 'qariconnect-9b95c.firebasestorage.app',
    iosBundleId: 'com.example.qariConnect',
  );
}
